In [2]:
import csv
import numpy as np

filename = 'data/pima-indians-diabetes.csv'
raw_data = open(filename, 'r')
reader = csv.reader(raw_data, delimiter=',', quoting=csv.QUOTE_NONE)
x=list(reader)
data = np.array(x).astype('float')
print(data.shape)

(768, 9)


NUMPY

In [3]:
import numpy as np
filename = 'data/pima-indians-diabetes.csv'
raw_data = open(filename, 'rb')
data = np.loadtxt(raw_data, delimiter=",")
print(data)

[[  6. 148.  72. ... 627.  50.   1.]
 [  1.  85.  66. ... 351.  31.   0.]
 [  8. 183.  64. ... 672.  32.   1.]
 ...
 [  5. 121.  72. ... 245.  30.   0.]
 [  1. 126.  60. ... 349.  47.   1.]
 [  1.  93.  70. ... 315.  23.   0.]]


Pandas

In [4]:
import pandas as pd
filename = 'data/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(filename, names=names)
data

preg  plas  pres  skin  test  mass     pedi  age  class
0       6   148    72    35     0  33.6   627.00   50      1
1       1    85    66    29     0  26.6   351.00   31      0
2       8   183    64     0     0  23.3   672.00   32      1
3       1    89    66    23    94  28.1   167.00   21      0
4       0   137    40    35   168  43.1  2288.00   33      1
..    ...   ...   ...   ...   ...   ...      ...  ...    ...
763    10   101    76    48   180  32.9   171.00   63      0
764     2   122    70    27     0  36.8     0.34   27      0
765     5   121    72    23   112  26.2   245.00   30      0
766     1   126    60     0     0  30.1   349.00   47      1
767     1    93    70    31     0  30.4   315.00   23      0

[768 rows x 9 columns]

URL

In [5]:
import pandas as pd
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/abalone/abalone.data"
df = pd.read_csv(url, header=None)
df

0      1      2      3       4       5       6       7   8
0     M  0.455  0.365  0.095  0.5140  0.2245  0.1010  0.1500  15
1     M  0.350  0.265  0.090  0.2255  0.0995  0.0485  0.0700   7
2     F  0.530  0.420  0.135  0.6770  0.2565  0.1415  0.2100   9
3     M  0.440  0.365  0.125  0.5160  0.2155  0.1140  0.1550  10
4     I  0.330  0.255  0.080  0.2050  0.0895  0.0395  0.0550   7
...  ..    ...    ...    ...     ...     ...     ...     ...  ..
4172  F  0.565  0.450  0.165  0.8870  0.3700  0.2390  0.2490  11
4173  M  0.590  0.440  0.135  0.9660  0.4390  0.2145  0.2605  10
4174  M  0.600  0.475  0.205  1.1760  0.5255  0.2875  0.3080   9
4175  F  0.625  0.485  0.150  1.0945  0.5310  0.2610  0.2960  10
4176  M  0.710  0.555  0.195  1.9485  0.9455  0.3765  0.4950  12

[4177 rows x 9 columns]

Estadistica descriptiva

In [6]:
import pandas as pd
filename = 'data/pima-indians-diabetes.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
data = pd.read_csv(filename, names=names)
data

preg  plas  pres  skin  test  mass     pedi  age  class
0       6   148    72    35     0  33.6   627.00   50      1
1       1    85    66    29     0  26.6   351.00   31      0
2       8   183    64     0     0  23.3   672.00   32      1
3       1    89    66    23    94  28.1   167.00   21      0
4       0   137    40    35   168  43.1  2288.00   33      1
..    ...   ...   ...   ...   ...   ...      ...  ...    ...
763    10   101    76    48   180  32.9   171.00   63      0
764     2   122    70    27     0  36.8     0.34   27      0
765     5   121    72    23   112  26.2   245.00   30      0
766     1   126    60     0     0  30.1   349.00   47      1
767     1    93    70    31     0  30.4   315.00   23      0

[768 rows x 9 columns]

Head

In [9]:
data.head(2)


preg  plas  pres  skin  test  mass   pedi  age  class
0     6   148    72    35     0  33.6  627.0   50      1
1     1    85    66    29     0  26.6  351.0   31      0

In [10]:
data.shape

(768, 9)

In [11]:
data.dtypes

preg       int64
plas       int64
pres       int64
skin       int64
test       int64
mass     float64
pedi     float64
age        int64
class      int64
dtype: object

# Describir

describe

In [18]:

data.describe()

preg        plas        pres        skin        test        mass         pedi  \
count  768.000000  768.000000  768.000000  768.000000  768.000000  768.000000   768.000000   
mean     3.845052  120.894531   69.105469   20.536458   79.799479   31.992578   428.235091   
std      3.369578   31.972618   19.355807   15.952218  115.244002    7.884160   340.485655   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000     0.100000   
25%      1.000000   99.000000   62.000000    0.000000    0.000000   27.300000   205.000000   
50%      3.000000  117.000000   72.000000   23.000000   30.500000   32.000000   337.000000   
75%      6.000000  140.250000   80.000000   32.000000  127.250000   36.600000   591.500000   
max     17.000000  199.000000  122.000000   99.000000  846.000000   67.100000  2329.000000   

              age       class  
count  768.000000  768.000000  
mean    33.240885    0.348958  
std     11.760232    0.476951  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     41.000000    1.000000  
max     81.000000    1.000000

### groupby('class').size()
Distribucion entre clases

In [38]:
# Pairwise Pearson correlations
pd.set_option('display.width', 100)
correlation = data.corr(method='pearson')
print(correlation)

           preg      plas      pres      skin      test      mass      pedi       age     class
preg   1.000000  0.129459  0.141282 -0.081672 -0.073535  0.017683 -0.026205  0.544341  0.221898
plas   0.129459  1.000000  0.152590  0.057328  0.331357  0.221071  0.133163  0.263514  0.466581
pres   0.141282  0.152590  1.000000  0.207371  0.088933  0.281805  0.051436  0.239528  0.065068
skin  -0.081672  0.057328  0.207371  1.000000  0.436783  0.392573  0.154274 -0.113970  0.074752
test  -0.073535  0.331357  0.088933  0.436783  1.000000  0.197859  0.185207 -0.042163  0.130548
mass   0.017683  0.221071  0.281805  0.392573  0.197859  1.000000  0.103575  0.036242  0.292695
pedi  -0.026205  0.133163  0.051436  0.154274  0.185207  0.103575  1.000000  0.017970  0.176608
age    0.544341  0.263514  0.239528 -0.113970 -0.042163  0.036242  0.017970  1.000000  0.238356
class  0.221898  0.466581  0.065068  0.074752  0.130548  0.292695  0.176608  0.238356  1.000000


### Asimetria: skew()